Update lint.yml

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -17,11 +17,7 @@ jobs:
   print_title_of_pr:
     runs-on: ubuntu-latest
     steps:
-    - name : Check Title of PR
-      if: startsWith(github.event.pull_request.title, ${{ fromJSON('["OVD","FVT","No-JIRA"]') }})
-      id: pr_title
-      run: echo The Title of your PR is ${{ github.event.pull_request.title }}
-    - name: Fail PR Title
-      if: steps.pr_title.outcome == 'skipped'
-      run: echo "Failed because Pull Request requires OVD-#### or FVT-####."; exit 1
+    - name : Fail PR 
+      if: ${{ !startsWith(github.event.pull_request.title, fromJSON('["OVD","FVT","No-JIRA"]'))}}
+      run: echo "Failed because Pull Request requires OVD-####, FVT-#### or No-JIRA."; exit 1
   
