Update pull_request.yml

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -26,19 +26,27 @@ jobs:
       - name: Add Reviewers
         run: echo "Adding team as reviewers"
   add-required-reviewer:
-    if: ${{ github.event.review.state == 'approved' && github.event.review.user != 'changtyler' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
+    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
     runs-on: ubuntu-latest
     needs: add-reviewers
     steps:
       - name: Add Required Reviewer
-        run: echo "Adding a required reviewer"
-  check-required-approval:
-    if: ${{ github.event.review.state == 'approved' && github.event.review.user == 'changtyler' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
-    runs-on: ubuntu-latest
-    needs: add-reviewers
-    steps:
+        if: github.event.review.user != 'changtyler'
+        id: reviewer
+        run: echo "Adding a required reviewer"; exit 1
       - name: Check Required Approval
+        if: github.event.review.user == 'changtyler'
+        id: approval
         run: echo "Approved - you may now merge your Pull Request."
+      - name: Do Not Merge
+        if: steps.approval.outputs.status == 'skipped'
+        run: exit 1
+#   check-required-approval:
+#     if: ${{ github.event.review.state == 'approved' && github.event.review.user == 'changtyler' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
+#     runs-on: ubuntu-latest
+#     needs: add-reviewers
+#     steps:
+      
   check-passing-job:
     if: ${{ jobs.check-required-approval.result == 'skipped' }}
     runs-on: ubuntu-latest
