Update pull_request.yml

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -27,10 +27,7 @@ jobs:
     needs: make-lint
     steps:
       - name: Add Reviewers
-        run: echo "Adding team as reviewers"; echo ${{ env.CONTINUE_ON_ERROR }}
-      - name: check env
-        if: ${{ env.CONTINUE_ON_ERROR }} == false
-        run: echo ${{ env.CONTINUE_ON_ERROR }}
+        run: echo "Adding team as reviewers"
   add-required-reviewer:
     if: ${{ github.event.review.state == 'approved' && github.actor != 'changtyler' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
     runs-on: ubuntu-latest
@@ -39,6 +36,7 @@ jobs:
       - name: Add Required Reviewer
         run: echo "Adding a required reviewer - "; echo "changtyler"
   check-required-approval:
+    if: github.event_name == 'pull_request_review'
     runs-on: ubuntu-latest
     needs: add-reviewers
     steps:
@@ -47,7 +45,33 @@ jobs:
         id: approval
         run: echo "Approved - you may now merge your Pull Request."
       - name: Skipped
-        if: steps.approval.outcome == 'skipped' && github.event_name == 'pull_request_review'
-        shell: bash
-        continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
+        if: steps.approval.outcome == 'skipped' && ${{ env.CONTINUE_ON_ERROR == false }}
         run: echo "Skipped because PR requires approvals."; exit 1
+      - id: timestamp
+        run: echo "::set-output name=timestamp::$(timestamp +%s)"
+#       - name: Pass
+#         if: steps.approval.outcome == 'skipped' && ${{ env.CONTINUE_ON_ERROR == true }}
+#         run: exit 0
+#       - name: Re-run failed test
+#         if: steps.approval.outcome == 'sucess' && ${{ env.CONTINUE_ON_ERROR == false }}
+#         run: exit 0
+      - name: Restore the previous run result
+        uses: actions/cache@v2
+        with:
+          path: |
+            run_result
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}-
+      
+      - name: Get the previous run result
+        id: run_result
+        run: cat run_result 2>/dev/null || echo 'default'
+
+      - uses: actions/checkout@v2
+        if: steps.run_result.outputs.run_result != 'success'
+
+      - if: steps.run_result.outputs.run_result != 'success'
+        run: echo "I'm alive!" && exit 0
+
+      - run: echo "::set-output name=run_result::success" > run_result
